CREATE FUNCTION get_colorSeq RETURN NUMBER IS
BEGIN
	RETURN D_COLOR_SEQ.nextval;
END;

-- DROP FUNCTION get_colorSeq;

CREATE SEQUENCE d_extension_seq
INCREMENT BY 1
START WITH 1;

CREATE FUNCTION get_extensionSeq RETURN NUMBER IS
BEGIN
	RETURN D_EXTENSION_SEQ.nextval;
END;

-- DROP FUNCTION get_extensionSeq;


